import Head from "next/head";
import Layout from "@/layout";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout metaTitle="Marcell">
        <h3>ini halaman Home</h3>
        <Link href="/users" className="bg-gray-200 p-2 rounded-xl ">
          Tugas ke 8 - Dynamic Router App
        </Link>
      </Layout>
    </>
  );
}
