import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import CardApi from "@/components/Card";
import { useRouter } from "next/router";

import dynamic from "next/dynamic";

const LayoutComponent = dynamic(() => import("@/layout"));

export default function Home() {
  const [data, setData] = useState([]);
  useEffect(() => {
    fetch("api/hello")
      .then((res) => res.json())
      .then((res) => {
        console.log(res);
        setData(res.users);
      })
      .catch((err) => console.log(err));
  }, []);

  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutComponent metaTitle="Marcell">
        <h3>ini halaman Home</h3>
        <Link href="/users" className="bg-gray-200 p-2 rounded-xl ">
          Tugas ke 8 - Dynamic Router App
        </Link>
        <section className=" bg-gray-200/30 w-full">
          <h3>Tugas Harian 9</h3>
          <div className="flex gap-2 flex-wrap justify-center items-center">
            {data.slice(0, 6).map((data) => (
              <CardApi key={data.id} card={data} />
            ))}
          </div>
        </section>
        <section>
          <h3>Tugas Harian 10</h3>
          <div className="flex gap-2 max-h-36">
            <Image src="/img.jpg" width={400} height={400} />
            <img src="/img.jpg" style={{ width: 400 }} />
          </div>
        </section>
      </LayoutComponent>
    </>
  );
}
